### ISSUE TITLE
could you tell me your own results of Conv-TasNet?

### ISSUE THREAD

**Issue by Reckless564** [JusperLee/Conv-TasNet#1]
hi, JusperLee, 
Your codes seem not the latest version of Conv-TasNet, I think it maybe the 2nd version of TasNet, because there is absent for the summation of all outputs from 1-D convblock ,the 1-D convblock is also lose the two path of outputs.
My codes add them but the results are not ideal, even less than the 2nd version, only 15.3dB.

Looking forward to your reply!

**Comment by JusperLee** [comment]
You can see in his article that his final SNR result is 15.3 and SDR is 15.6. At the same time, you can see in the github open source library (https://github.com/naplab/Conv-TasNet) given by him that he actually separated the two paths, and only used one path method for training. When I tested these two paths, I found that the combination of the output and the previous input works better.
![image](https://user-images.githubusercontent.com/33806018/70861633-d85a9c00-1f6b-11ea-9899-96ec405209fc.png)

**Comment by Reckless564** [comment]
Thanks for your reply!

**Comment by JusperLee** [comment]
> Thanks for your reply!

our result:
1. Average SNR: 15.39008
2. Average SDR: 15.81919

**Comment by JusperLee** [comment]
@Reckless564 I updated the model code and will do a sum of skip_connection. The end result is SNR 15.3.
