### ISSUE TITLE
噪声问题

### ISSUE THREAD

**Issue by fanmanqian** [JusperLee/Conv-TasNet#14]
作者您好，非常感谢您提供的代码，这份代码我运行了，在测试的时候，分离效果几乎很小，反而还增加了噪声，现在就是有几个小问题，和这份代码无关的小问题，我是在自己的数据集上跑的，我把自己的数据集切成了3s的然后随机混合，train 16800条,val 4200条，是不是我在测试的时候就是运行Seperation.py得加一个专门的test集，这个test集可不可以直接用val呢？还是说得再重做呢？还有一个问题就是音频长度是否会影响实验结果呢？3s的会不会太短了？

**Comment by JusperLee** [comment]
test最好是val和train没有出现过的数据集，音频长度对结果影响不大。convtasnet对含有噪声的数据集效果本身就不好，你可能需要加入其他的trick

**Comment by fanmanqian** [comment]
好哒，谢谢您~
 
---原始邮件---
发件人: "Kai Li (李凯)"<notifications@github.com&gt;
发送时间: 2020年9月1日 10:10:15
收件人: "JusperLee/Conv-TasNet"<Conv-TasNet@noreply.github.com&gt;;
抄送: "fanmanqian"<2563965485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [JusperLee/Conv-TasNet] 噪声问题 (#14)




 
test最好是val和train没有出现过的数据集，音频长度对结果影响不大。convtasnet对含有噪声的数据集效果本身就不好，你可能需要加入其他的trick

**Comment by hong1997-12** [comment]
对两个纯净语音分离效果也很差怎么回事，复现达不到公开的结果，相差很多

**Comment by JusperLee** [comment]
你是使用的WSJ数据集么？我在WSJ数据集上测试的结果是超过论文结果的

> 对两个纯净语音分离效果也很差怎么回事，复现达不到公开的结果，相差很多

**Comment by hong1997-12** [comment]
用的LibriMix的数据集，我看他论文上说是可以用原论文那么高的

**Comment by JusperLee** [comment]
> 用的LibriMix的数据集，我看他论文上说是可以用原论文那么高的

那篇论文呢？Conv-TasNet没有用LibriMix吧？

**Comment by hong1997-12** [comment]
LibriMix: An Open-Source Dataset for Generalizable Speech Separation
这篇论文

**Comment by JusperLee** [comment]
> LibriMix: An Open-Source Dataset for Generalizable Speech Separation
> 这篇论文

你自己训练的结果能差多少呢？因为我没有对LibriMix进行测试，你可以调整模型参数或者数据预处理的方法，模型结构是完全符合Conv-TasNet的结构。

**Comment by hong1997-12** [comment]
差的挺多的，就不知道具体问题出在哪了

**Comment by JusperLee** [comment]
你可以再仔细检查下，我认为代码没有什么问题，你可以试试asteroid：https://github.com/mpariente/asteroid。或者对比一下两个配置

**Comment by hong1997-12** [comment]
好的谢谢

**Comment by myAnonymous** [comment]
大佬您好！非常感谢您提供的这份代码。我有几个问题想要请教一下：我在复现的时候跑不出原文的效果，是不是需要对数据做什么样的预处理？您合成混合语音就是直接用您提到的matlab脚本吗？我发现里面的.txt涉及到的部分语音在我的数据集里面不存在，会是因为我获得的WSJ0数据集不完整吗？以及您用于合成语音的是 “chime2_wsj0/data/chime2_wsj0/isolated/*” 下面的语音数据吗？
非常感谢！

**Comment by zheng-awei** [comment]
> 好的谢谢

你好，我最近在复现ConvTasNet时也发现无法达到和Librimix论文中所说的结果，想请教一下你是否解决了这个问题？如何解决的呢？

**Comment by JusperLee** [comment]
目前已经解决！
