### ISSUE TITLE
中断

### ISSUE THREAD

**Issue by fanmanqian** [JusperLee/Conv-TasNet#15]
作者，您好，我这边训练conv_tasnet，训练了一周了到53轮，时候突然中断了，可以从断的地方继续训练么？如果可以的话，是修改哪里呢？yml里面的resume么？

**Comment by fanmanqian** [comment]
已解决~

**Comment by JusperLee** [comment]
![image](https://user-images.githubusercontent.com/33806018/92942636-4fce4500-f484-11ea-812f-89764c248196.png)
改为True，加上pt文件的路径
