### ISSUE TITLE
复现结果问题

### ISSUE THREAD

**Issue by enhancer12** [JusperLee/Conv-TasNet#16]
大佬您好！非常感谢您提供的这份代码。我有几个问题想要请教一下：我在复现的时候跑不出原文的效果，是不是需要对数据做什么样的预处理？您合成混合语音就是直接用您提到的matlab脚本吗？我发现里面的.txt涉及到的部分语音在我的数据集里面不存在，会是因为我获得的WSJ0数据集不完整吗？以及您用于合成语音的是 “chime2_wsj0/data/chime2_wsj0/isolated/*” 下面的语音数据吗？
非常感谢！

**Comment by JusperLee** [comment]
首先，wsj0数据有两个版本，其中一个是含有噪声的，另一个是干净的。我们一般使用的是干净的作为wsj0数据集。合成混合语音使用dpcl提供的matlab脚本。我运行该代码是没有问题的，可能是你的数据集不完整。kaldi下面的这个数据集我不太了解，只要是wsj0就可以了。
