### ISSUE TITLE
Train for Music Source Separation

### ISSUE THREAD

**Issue by shoegazerstella** [JusperLee/Conv-TasNet#21]
Hi,
I would like to know if you would suggest using this architecture for the task of Music Source Separation and also what changes with respect to this other approach called [demucs](https://github.com/facebookresearch/demucs).
Thanks a lot!

**Comment by JusperLee** [comment]
I think this method can perform the task of music separation. In fact, the structures of these two models are completely different, one is tcn and the other is u-net.

**Comment by shoegazerstella** [comment]
It seems they have adapted the same Conv-TasNet from [kaituoxu/Conv-TasNet ](https://github.com/kaituoxu/Conv-TasNet)
As they state in the README:

```
Conv-Tasnet is a separation model developed for speech which predicts a mask on a learnt over-complete linear representation using a purely convolutional model with stride of 1 and dilated convolutional blocks. We reused the code from the kaituoxu/Conv-TasNet repository and added support for multiple audio channels.
```

I guess yours and the other one are almost the same, right?

**Comment by JusperLee** [comment]
yes, you are right. Our model structures are the same.
