### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by WAN-L** [JusperLee/Conv-TasNet#22]
大佬您好，我刚开始跑代码，训练的时候有一个错误是说在validation model 那部分，trainer.py里面
total_loss_avg = sum(losses)/len(losses)
ZeroDivisionError: division by zero   ，这个losses为0是什么原因呢？
谢谢！

**Comment by aha1020** [comment]
请问您解决了吗？

**Comment by JusperLee** [comment]
> 请问您解决了吗？

应该是一开始没有loss，所以长度为0，你可以加一个判断，一开始的validation不做loss。
