### ISSUE TITLE
DataLoaders到底是在干嘛

### ISSUE THREAD

**Issue by hhetui** [JusperLee/Conv-TasNet#24]
重新写一个Dataloader那个__iter__的意义是什么啊

**Comment by JusperLee** [comment]
我有想的是能把所有的语音都用上，而不是简单切断。

**Comment by hhetui** [comment]
![image](https://user-images.githubusercontent.com/43748281/115176396-99a89900-a0ff-11eb-9473-a5c7ac608fef.png)
这个部分，从上面的dataloader中拿出来然后又返回 不太理解意义

**Comment by JusperLee** [comment]
长度固定，有一些可能长度不太一样

**Comment by wxystudio** [comment]
作者应该是参考了funcwj同学，你也可以把数据处理放到dataset函数里面，datalodar只用于返回迭代器~

**Comment by JusperLee** [comment]
> 作者应该是参考了funcwj同学，你也可以把数据处理放到dataset函数里面，datalodar只用于返回迭代器~

可以看lightning版本是直接处理了统一的长度
