### ISSUE TITLE
LibriSpeech 数据集训练

### ISSUE THREAD

**Issue by guggugg** [JusperLee/Conv-TasNet#25]
你好，我使用LibriSpeech 数据集混合了20000个语音进行训练，但下降并不是很明显，且在70多epoch的时候就early stop了 损失只下降到-7.几，请问可能有哪些原因呢

**Comment by JusperLee** [comment]
你用的是哪个文件夹的代码？LibriSpeech的混合应该结果不会很差的。

**Comment by guggugg** [comment]
pytorch那个

**Comment by JusperLee** [comment]
不应该吧，你也可以试试lightning的版本。我在wsj的结果应该是没问题的。或者你可以检查一下yml的配置文件
