### ISSUE TITLE
Example of output

### ISSUE THREAD

**Issue by nanometer34688** [JusperLee/Conv-TasNet#3]
Hi @JusperLee 

I have used your pre trained weights and inferred on 1 mixed wav file found here: https://www.merl.com/demos/deep-clustering/media/male-male-mixture.wav.

The output contains a very high pitched tone and hard to hear audio.

Have you experienced this as well when inferring?

Thanks

**Comment by JusperLee** [comment]
I think you may have used the script incorrectly. You can check it. Below is my result.

[mix.zip](https://github.com/JusperLee/Conv-TasNet/files/4442289/mix.zip)
