### ISSUE TITLE
using pre-train model error

### ISSUE THREAD

**Issue by boun780** [JusperLee/Conv-TasNet#32]
你好，我使用你在readme中提供的预训练模型best.pt对一段混合语音进行测试，在保存音频文件时出现以下错误，请问该如何解决呢
![QQ图片20211217220217](https://user-images.githubusercontent.com/58206033/146555857-e260610a-c326-4478-be82-e858913364da.jpg)

**Comment by JusperLee** [comment]
维度不一样，把音频维度降为一维

**Comment by boun780** [comment]
>

**Comment by boun780** [comment]
你好，我用下面的代码改为1D后，
`s = s.reshape(-1, 1)`
` write_wav(filename, s, 8000)`
又出现新的错误，请问您知道如何解决吗，谢谢~
![image](https://user-images.githubusercontent.com/58206033/146705506-80fcc5c3-bbca-4efc-b6b6-5c7e63d2b438.png)

**Comment by boun780** [comment]
你好，我使用这段音频：https://www.merl.com/demos/deep-clustering/media/male-male-mixture.wav 进行了测试，但是得到的结果并没有将其分离开，请问您有什么建议吗？谢谢~
这是得到的音频结果：链接：https://pan.baidu.com/s/1Z-YdfeG3Bb77b-w_pfPiFg 
提取码：k9e6

**Comment by JusperLee** [comment]
我这边没有问题还是可以进行分离，你可以重新训练或者你再检查是否有别的问题。

**Comment by boun780** [comment]
你好，请问你使用的是readme中给出的预训练模型吗？best.pt还是last.pt？

**Comment by JusperLee** [comment]
best.pt，我推荐你使用代码重新训练

**Comment by Meng-Li-Ya** [comment]
同样遇到这个维度问题，可以请问一下具体的修改步骤吗，万分感谢

**Comment by ElunaMamka** [comment]
同样是遇到这个问题，请问具体如何降维呢

**Comment by NJUPTgaf** [comment]
> 

unsqueeze

**Comment by PANPANKK** [comment]
同样遇到这个维度问题，可以请问一下具体的修改步骤吗，万分感谢

**Comment by NJUPTgaf** [comment]
> 同样遇到这个维度问题，可以请问一下具体的修改步骤吗，万分感谢

我是这样改的。
![image](https://user-images.githubusercontent.com/53931483/225196055-f09fde7b-730f-41b3-a4c1-aad08a978718.png)

**Comment by PANPANKK** [comment]
> > 同样遇到这个维度问题，可以请问一下具体的修改步骤吗，万分感谢
> 
> 我是这样改的。 ![image](https://user-images.githubusercontent.com/53931483/225196055-f09fde7b-730f-41b3-a4c1-aad08a978718.png)

谢谢你，问题解决了
