### ISSUE TITLE
problem about music source separation

### ISSUE THREAD

**Issue by yudashuixiao1** [JusperLee/Conv-TasNet#33]
你好，我第一次用conv-tasnet，我用的是musdb数据集，采样用44100，用做分离语音vocals和背景音accompaniment音色，loss一直在10+下不去。请问你有做过用这样的尝试么，不知道我哪里出了问题。。。由于我gpu内存不够，chunk_size改成了44100,其他训练参数不变。

**Comment by JusperLee** [comment]
我没有尝试过musdb的数据，你可以先用wsj来验证一下是否是因为代码出现的问题。
