### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by Meng-Li-Ya** [JusperLee/Conv-TasNet#34]
![2022-01-24](https://user-images.githubusercontent.com/98250245/150725964-63d0a055-d099-4a77-ae9f-1d04ca86631f.png)
请问测试单个音频时46行的key是什么，没有找到它的定义，希望您能指出它的解决方法，万分感谢

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Conv-TasNet/blob/9eac70d28a5dba61172ad39dd9fb90caa0d1a45f/Conv_TasNet_Pytorch/Separation_wav.py#L46

你把key换成一个文件名称就行
