### ISSUE TITLE
从option包中引用parse报错

### ISSUE THREAD

**Issue by Meng-Li-Ya** [JusperLee/Conv-TasNet#35]
![2022-02-28](https://user-images.githubusercontent.com/98250245/155978945-189ed575-563c-421d-a83d-c23b374eadfc.png)
请问这个怎么解决

**Comment by van7777777** [comment]
请问你解决了吗

**Comment by JusperLee** [comment]
用命令行cd到separation文件夹里执行命令，不要直接运行应该可以解决

**Comment by van7777777** [comment]
> 用命令行cd到separation文件夹里执行命令，不要直接运行应该可以解决

感谢您的回复！刚才我用命令行执行，但是报错还是和pycharm内部一样

**Comment by JusperLee** [comment]
我尽快查清问题

**Comment by van7777777** [comment]
> 我尽快查清问题

谢谢！train.py也有类似的情况。

**Comment by JusperLee** [comment]
![image](https://user-images.githubusercontent.com/33806018/156704750-0c72d609-f64b-45bf-996e-01fed8cd3a39.png)
我没有遇到这种情况我怀疑是pycharm的原因，你可以使用vscode+命令行方式训练
```python
python train.py -opt ./options/train/train.yml
```

**Comment by van7777777** [comment]
谢谢！我去尝试下
