### ISSUE TITLE
有关model_size

### ISSUE THREAD

**Issue by AIHHU** [JusperLee/Conv-TasNet#38]
学长好，我看这个论文里结果model_size连10m都不到，为什么宁的模型大小有30m呢？

**Comment by JusperLee** [comment]
你改一下参数，按照论文修改参数

**Comment by AIHHU** [comment]
学长，我正好看到您也跑过sudo_rm_rf，请问您跑下来分离效果怎么样，为什么我这边明明si-sdr达到了15.0，为什么跑出来能听到那么多噪声呢？
