### ISSUE TITLE
integrate into onssen?

### ISSUE THREAD

**Issue by nateanl** [JusperLee/Conv-TasNet#4]
Hi Jusper,
Thanks for sharing the Conv-TasNet implementation! I'm writing an open-source library to contain speech-separation algorithms, especially the deep learning ones. Would you like me to integrate your Conv-TasNet code into the [onssen](https://github.com/speechLabBcCuny/onssen) library? I will add the copyright header before I push it to the repo. Thanks!

**Comment by JusperLee** [comment]
My project itself is open source. You can add it to your code repository.

**Comment by nateanl** [comment]
Great, thanks!
