### ISSUE TITLE
关于Encoder与mask复现

### ISSUE THREAD

**Issue by van7777777** [JusperLee/Conv-TasNet#41]
请问该如何像论文中一样复现encoder与decoder的过程图呢？

**Comment by JusperLee** [comment]
你说的是频谱图的那个图还是什么？

**Comment by van7777777** [comment]
你好，是的，包括mask1与mask2, 不知道该如何可视化一下这个图

**Comment by JusperLee** [comment]
> 你好，是的，包括mask1与mask2, 不知道该如何可视化一下这个图

直接把后面的输出当做频谱可视化就好了。。。

**Comment by van7777777** [comment]
谢谢！
