### ISSUE TITLE
 硬件规格

### ISSUE THREAD

**Issue by MaizeKai** [JusperLee/Conv-TasNet#44]
您好，想请问您gpu规格是什摸，我使用RTX 3090，出现了CUDA out of memory，所以想跟您询问，谢谢

**Comment by JusperLee** [comment]
你可以减少batch size。我使用的是1080ti

**Comment by MaizeKai** [comment]
那想请问您大概batch size设多少呢？因为我要到8才能跑，跟原本设定的40差满多的，感谢

**Comment by JusperLee** [comment]
batch size=8，效果也能够达到论文的结果。
