### ISSUE TITLE
About the conv block architecture

### ISSUE THREAD

**Issue by LingweiMeng** [JusperLee/Conv-TasNet#45]
Hi Jusper, I noticed that you removed the second PReLU2 and Norm2 in the Conv1D Block in the latest version.
May I know why you did this? 
'Cause in the original paper they are there.

**Comment by JusperLee** [comment]
Since many people were asking why the performance was bad, I found that part of the reason was because of skip-connection, so I removed this operation to improve performance.

**Comment by LingweiMeng** [comment]
Thanks for the reply.  :)
