### ISSUE TITLE
model_size issue

### ISSUE THREAD

**Issue by will46616** [JusperLee/Conv-TasNet#46]
I have tried the parameter configuration on the paper, but the model size is still only about 3.5M, not up to the baseline of 5.1M. What else can I do to increase the model size besides modifying the yml file?

**Comment by JusperLee** [comment]
I think it's because I didn't add a skip connection.

**Comment by will46616** [comment]
Thank you for your reply. For adding skip connection, can users add skip connection by adjusting the parameters or the code?

**Comment by JusperLee** [comment]
You can see my previous submission. I later removed this part of the code because it did not align with the pre-trained model.

**Comment by will46616** [comment]
OK, I'll go check it out. Thanks.

**Comment by will46616** [comment]
Sorry, I have another question. I'm not quite sure which one is your previous conv tasnet submission. Is it in this link? https://github.com/JusperLee/Conv-TasNet/commit/1f413ba02d03e8db34f0c95af2d0b674a52b1e85

**Comment by JusperLee** [comment]
Yes

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Conv-TasNet/blob/master/Conv_TasNet_Pytorch/Conv-TasNet-Skip

**Comment by will46616** [comment]
Thanks !
