### ISSUE TITLE
Where is the scp file?

### ISSUE THREAD

**Issue by Amjid-Ali** [JusperLee/Conv-TasNet#50]
/home/likai/data1/Dataset/wsj0-mix/2speakers/wav8k/min/tr/mix in the generate_scp file you have given the file path. can you show me where these file are?

**Comment by Amjid-Ali** [comment]
when i train the generate_scp file. it generate files but empty.

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Conv-TasNet/blob/master/Conv_TasNet_Pytorch/create_scp.py

You need to run this code to generate the scp file.
