### ISSUE TITLE
DataLoaders_new 结尾的print函数的用处是什么

### ISSUE THREAD

**Issue by LackFuch** [JusperLee/Conv-TasNet#51]
训练模型时，里面显示index out of range ，查找原因，Dataloaders_new 运行时的结果为0，结尾的print函数不知道用处，老师您能帮忙解答下吗

**Comment by JusperLee** [comment]
查看一下输出的混合音频和目标音频

**Comment by LackFuch** [comment]
谢谢您的回答，还有个问题，在trainer函数里，有一个mse的值，括号中未给出量，请问下这一块的问题，如果您能回答，将万分感谢。

**Comment by LackFuch** [comment]
在trainer的170行，看其他对于该论文的实现没加mse，然后loss为啥在训练的时候为负值。

**Comment by JusperLee** [comment]
负值是因为训练的loss是sisnr，越大越好，而梯度则是朝向最小值下降，所以求负数
