### ISSUE TITLE
Where is the contribution of the Sc hyperparameter

### ISSUE THREAD

**Issue by nirmala-dewi** [JusperLee/Conv-TasNet#58]
Hello, I see you give 2 code with and without skip connection, but in the code with skip connection, I didn't find the contribution of the "sc" variable, can you tell me where it should be?

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Conv-TasNet/blob/1d05c4730e59034a0f3dfc8d0ee987f9988820b5/Conv_TasNet_Pytorch/Conv-TasNet-Skip#L166
